### PR TITLE
Fix powershell array parsing

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Can you explain the reason for that change?

Also we should avoid too many whitespace changes, and code should be linted and formatted using gofmt.

**Comment by RincewindsHat** [comment]
I encountered Service checks with arrays and the powershell-framework icinga configuration did not generate the nice `@()` format, but just as comma separated values which the connector does not parse correctly.
This was just a quick hot fix and on further examination, there are some problems with it, which I will fix.
But I left this here as a reminder to myself to bring the changes back in to the project.

**Comment by K0nne** [comment]
I encountered problems when I want to check an array of perfcounters with the powershell connector. Could this be related ([netways #758819])?

**Comment by K0nne** [comment]
The PR ist working.  My array problems are solved.

**Comment by RincewindsHat** [comment]
@K0nne Happy to hear it. I will look over this once more until I am halfway sure it does not break anything and the this can be merged.

**Comment by K0nne** [comment]
That's good to hear. The powershell connector is able to reduce the monitoring-inducted load by a few percent.

**Review by martialblog — APPROVED** [review]
LGTM

**Pull request merged**
